### ISSUE TITLE
プログラム3D実行画面とGoogle Blockly部分の連結

### ISSUE THREAD

**Issue by shundroid** [j-code-org/three-blockly#2]
まだこの部分のつながりは実装されていない感じでしょうか。とすると、しばらくはここの部分を重点的に書いていく感じになりますかね。

**Comment by koichii** [comment]
実装済みです。シーンに追加してないのでは？（ここがわかりにくいので、改善したいと思っています）

1. 以下２ブロックをプログラミングする。

　obj = 新しい たま
　シーンに obj を追加

```
var obj;
obj = new THREE.library["sphere"]();
THREE.scene.add (obj);
```

2.「実行」ボタンをクリック。画面に「たま」が出ます。

**Comment by shundroid** [comment]
今確認しました。ほんとですね、出ました。失礼しました。

Run ボタンと実行ボタンが違うってことなのですね。
