### ISSUE TITLE
jQueryとバニラの統一

### ISSUE THREAD

**Issue by shundroid** [j-code-org/three-blockly#3]
jQueryで書かれている場所と、 `document.getElementById(...)` (バニラ)で書かれている場所の混在が見られたのですが、これは今後書く場合に迷ってしまいそうなので、どちらかに統一していただけませんでしょうか。

個人的には、jQueryはオワコンなのではないかと思っておりますので、後者で統一していく方向にしていただきたいです。

**Comment by koichii** [comment]
JQuery 全盛の頃につくりはじめた為の残骸なので、jQuery なくす方向（バニラ）でいきましょう。
