### ISSUE TITLE
色が変わらない

### ISSUE THREAD

**Issue by shundroid** [j-code-org/three-blockly#5]
![image](https://user-images.githubusercontent.com/8530218/76925690-9ac82f00-691d-11ea-88f7-14609d2962e7.png)
これをやっても、黄色のままです

**Comment by koichii** [comment]
これはバグです！
直接的には、「async function colourRgb」は、本来「function colourRgb」でasync無しで良いのに、 async が頭についているのが不具合の原因です。

もともと関数のブロックはJavaScript の function に翻訳され実行されます。
しかしながら、オブジェクトを動かす処理等で、async/await が必要になりましたため、生成された javascript の実行前にむりやり「 function 」を 「async function」 に変換してます。
その副作用で、いろいろと矛盾が発生しており、困ってます・・・

**Comment by shundroid** [comment]
うーんなるほど、asyncにされたのは、「30cm前に進む」みたいな処理を待つためですかね。
async にするfunctionを選択的に指定できるようにするか、もしくは全関数呼び出しにawaitを付けることで対処できませんかね…

**Comment by koichii** [comment]
関数ブロックを拡張して、async にするfunctionを選択的に指定できるようにしたいです。
